export enum Route {
  HOME = '/',
  LANDING = '/landing-v2',
  LOGIN = '/auth/login',
  REGISTER = '/auth/register',
  FORGOT_PASSWORD = '/auth/forgot-password',
  STUDIO = '/studio',
  STUDIO_CANVAS = '/studio/canvas-editor',
  STUDIO_DIALOGUE = '/studio/dialogue-editor',
  STUDIO_GENERATE = '/studio/generate-clean',
  STUDIO_PREVIEW = '/studio/preview',
  PROFILE = '/profile',
  COMMUNITY = '/community',
  PRICING = '/pricing',
  ERROR = '/error',
}

export const PUBLIC_ROUTES = [
  Route.HOME,
  Route.LANDING,
  Route.LOGIN,
  Route.REGISTER,
  Route.ERROR,
];

export const ROUTE_METADATA: Record<
  Route,
  { title: string; description?: string }
> = {
  [Route.HOME]: {
    title: 'Manga Studio - Create AI Manga Art',
    description:
      'Generate stunning manga illustrations with AI. Design custom manga pages with professional inking styles, screentones, and layouts.',
  },
  [Route.LANDING]: {
    title: 'Manga Studio - Create AI Manga Art',
    description:
      'Generate stunning manga illustrations with AI. Design custom manga pages with professional inking styles, screentones, and layouts.',
  },
  [Route.LOGIN]: {
    title: 'Sign In | Manga Studio',
    description: 'Sign in to access your manga studio and creations.',
  },
  [Route.REGISTER]: {
    title: 'Create Account | Manga Studio',
    description: 'Sign up to start creating your own AI manga art.',
  },
  [Route.FORGOT_PASSWORD]: {
    title: 'Forgot Password | Manga Studio',
  },
  [Route.STUDIO]: {
    title: 'Your Projects | Manga Studio',
    description: 'Manage and create your manga projects.',
  },
  [Route.STUDIO_CANVAS]: {
    title: 'Canvas Editor | Manga Studio',
    description: 'Edit your manga panels and layouts in the Canvas.',
  },
  [Route.STUDIO_DIALOGUE]: {
    title: 'Dialogue Editor | Manga Studio',
    description: 'Write scripts and edit dialogue for your manga.',
  },
  [Route.STUDIO_GENERATE]: {
    title: 'AI Generator | Manga Studio',
    description: 'Generate new manga panels and characters with AI.',
  },
  [Route.STUDIO_PREVIEW]: {
    title: 'Preview Project | Manga Studio',
  },
  [Route.PROFILE]: {
    title: 'Profile Settings | Manga Studio',
  },
  [Route.COMMUNITY]: {
    title: 'Community Gallery | Manga Studio',
    description: 'Explore manga art generated by the Manga Studio community.',
  },
  [Route.PRICING]: {
    title: 'Pricing | Manga Studio',
    description: 'Purchase credit packs to generate your manga stories.',
  },
  [Route.ERROR]: {
    title: 'Error | Manga Studio',
  },
};
